[package]
name    = "db-config"
version.workspace = true
edition.workspace = true

[[bin]]
name = "db_config"
path = "src/main.rs"

[dependencies]
btr-types.workspace = true
clap.workspace      = true
rusqlite.workspace  = true
thiserror.workspace = true
odbc-api.workspace  = true
postgres            = "0.19"
