use crate::db;
use crate::export as render;
use std::path::{Path, PathBuf};

pub fn do_export_int(db_path: &Path, out_dir: &Path, tables: &[String]) -> Result<(), String> {
    let conn = db::open(db_path).map_err(|e| e.to_string())?;
    let server = db::get_config(&conn, "config", "SERVER")
        .map_err(|e| e.to_string())?
        .unwrap_or_default();

    std::fs::create_dir_all(out_dir).map_err(|e| e.to_string())?;

    let names: Vec<String> = if tables.is_empty() {
        db::list_tables(&conn)
            .map_err(|e| e.to_string())?
            .into_iter()
            .map(|r| r.table_name)
            .collect()
    } else {
        tables.to_vec()
    };

    let mut count = 0;
    for name in &names {
        let f = db::get_table(&conn, name, None)
            .map_err(|e| e.to_string())?
            .ok_or_else(|| format!("table '{name}' not found"))?;
        let text = render::render_int(&f, &server);
        let filename = render::int_filename(&f);
        let path = out_dir.join(&filename);
        std::fs::write(&path, text).map_err(|e| e.to_string())?;
        println!("  wrote {}", path.display());
        count += 1;
    }
    println!("{count} INT files written.");
    Ok(())
}

pub fn do_export_mds(db_path: &Path, out_file: &Path) -> Result<(), String> {
    let conn = db::open(db_path).map_err(|e| e.to_string())?;
    let rows = db::get_all_config(&conn).map_err(|e| e.to_string())?;
    let text = render::render_mds(&rows);
    std::fs::write(out_file, text).map_err(|e| e.to_string())?;
    println!("wrote {}", out_file.display());
    Ok(())
}

pub fn do_gen_ddl(
    db_path: &Path,
    out: Option<&PathBuf>,
    add_recnum: bool,
    tables: &[String],
) -> Result<(), String> {
    let conn = db::open(db_path).map_err(|e| e.to_string())?;

    let names: Vec<String> = if tables.is_empty() {
        db::list_tables(&conn)
            .map_err(|e| e.to_string())?
            .into_iter()
            .map(|r| r.table_name)
            .collect()
    } else {
        tables.to_vec()
    };

    let mut ddl = String::new();
    ddl.push_str("-- Generated by db_config\n-- Target: SQL Server\n\n");

    for name in &names {
        let f = db::get_table(&conn, name, None)
            .map_err(|e| e.to_string())?
            .ok_or_else(|| format!("table '{name}' not found"))?;
        ddl.push_str(&render::render_ddl(&f, add_recnum));
        ddl.push('\n');
    }

    if let Some(path) = out {
        std::fs::write(path, &ddl).map_err(|e| e.to_string())?;
        println!("wrote {} tables to {}", names.len(), path.display());
    } else {
        print!("{ddl}");
    }
    Ok(())
}
